# Generated by Django 2.1a1 on 2018-05-24 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='text',
            field=models.TextField(max_length=2000),
        ),
    ]
